# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('recruiting_numbers', models.IntegerField()),
                ('requirement', models.TextField()),
                ('duty', models.TextField()),
                ('more_info', models.TextField()),
                ('post_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiting_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.RecruitingCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.WorkLoc'),
        ),
    ]
